### ISSUE TITLE
Audit Template Checklist

### ISSUE THREAD

**Issue by adam-palazzo** [RichardLitt/extract-id3-tags-from-mp3s#11]
### Reviewing the Repository Docs

- [x] Is there a README?
  - [x] Does it follow [standard-readme](https://github.com/RichardLitt/standard-readme)?
  - [x] Is it spellchecked?
- [x] Is there a Code of Conduct, such as the [Contributor Covenant](https://github.com/simonv3/covenant-generator)?
  - [x] Is it mentioned in the Contribute section of the README? (Note: this isn't needed if you mention it in your CONTRIBUTE.md and it is in this repository.)
  - [ ] Does it reference an email address for violations?
*No, you requested we not include email addresses*
  - [ ] Does it reference a second email address?
*No, see above*
- [x] Is there a `LICENSE` file?
  - [x] Is this matched in the `package.json`?
  - [x] Is the year correct?
- [ ] Is there a `.github` or `docs` folder?
*Too small of a project to use a .github folder*
  - [ ] Is there an `ISSUE_TEMPLATE.md` or `ISSUE_TEMPLATE` folder ([example](https://github.com/babel/babel/issues/new/choose))?
*See Above*
  - [ ] Is there a `PULL_REQUEST_TEMPLATE.md`?
*See Above above*
- [x] Is there a `CONTRIBUTING.md` file?
  - [x] Does it mention how to make a PR?
  - [ ] Does it mention what sort of issues you'd like?
*Too small a project to specify issues*
  - [x] Does it mention a `good first issue` label as a starting point?
  - [ ] Does it mention triaging and bug reports as good starting points?
*Too small for this*
  - [x] Does it point to a community chat program, like Slack or Gitter?
  - [ ] Does it encourage conversations in issues before opening huge PRs?
*Too small for this*
  - [x] Does it specify where to ask questions on process?
  - [ ] Does it explain labels used in the issues?
*Not many labels*
- [ ] Is there a `CHANGELOG`?
*No, there is currently only one version of the file, and it is so small that a changelog seems redundant*
  - [ ] If there isn't, are notes included in the project's releases?
- [x] Does this pass [`alex`](https://github.com/wooorm/alex) adequately? Run `alex *.md`.
- [x] Does the repository name itself pass on http://wordsafety.com?
- [ ] Is there a locked updates issue to give users a single place to stay up-to-date without the need to watch the entire repository? ([example](https://github.com/octokit/rest.js/issues/620))
*No, too small a project for locked updates issue*
### Process
- [x] Can I install easily?
- [x] Can I use this easily?

### Issues and Pull Requests
- [x] Are there an acceptable amount of pull requests?
- [x] Are there an acceptable amount of issues?
- [x] Are an acceptable amount of issues less than six months old?
- [x] Are there useful issue labels?
- [ ] Are the labels being used?
*Not necessary*
- [x] Is there a `good for beginners` or `good first issue` label?
- [ ] Is there a `waiting on contributor` label?
*Not necessary*

### Bots

_Note: Neither of these are necessary, but they can help with some things. Check out https://probot.github.io/ for some tools._

- [ ] Are there bots enabled? *No*
- [ ] Are the bots listed in the Contribute or Readme files so that users can expect to interact with them?

### Metadata
- [x] Is there a description on GitHub?
*Will make issue*
  - [x] Does the description match the README?
- [x] Are the topics useful?
- [ ] Is there a website? *No need*
  - [ ] Does the website match the project?

### Package Metadata

Note: These should apply to `package.json` (JavaScript), `*.cabal` (Haskell), and `metadata.yml` (Perl), among others.

- [x] Does the description match the GitHub description?
*Not yet*
- [x] Is there a `bugs` field?
- [x] Is there a `homepage` field?
- [x] Are there appropriate `keywords`?
  - [x] Do these match the topics on GitHub?
- [x] Run [`depcheck`](https://www.npmjs.com/package/depcheck); do the deps make sense?

#### Generic
- [x] I would add a maintainers section, to make it clear who is on the maintainers team. This helps set expectations and clarifies for the users who they can talk to.

#### Issues
- [x] Add 'discussion' labels to longstanding issues. *N/A*

**Comment by RichardLitt** [comment]
Thanks @adam-palazzo. Can you go through and check off what is done, and comment on what isn't?
